### ISSUE TITLE
Error encountered while running SCASL

### ISSUE THREAD

**Issue by KaKa-sxyd** [xryanglab/SCASL#1]
Hello, I'm glad to see you have created such meaningful work. However, I encountered a little trouble when running her, and I look forward to your solution
I have configured the conda environment according to your configuration requirements file, but then I encountered the following error when running the sample data.

**python main.py -y configs/srr_star_demo.yaml**

![image](https://github.com/xryanglab/SCASL/assets/139625460/683b7fa6-ccd6-4603-a79d-2218f4eca19e)

I also run **python main.py -y configs/srr_demo.yaml**

![image](https://github.com/xryanglab/SCASL/assets/139625460/6d61eaa1-6f50-4168-852b-912419dc1159)

**Comment by kokox10** [comment]
Thank you for your interest. However, based solely on the information provided, it is difficult for me to accurately identify the problem. I can offer the following suggestions based on my personal experience:

1. Please verify if the version of pandas is consistent with the requirements.txt file. Many errors stem from version conflicts with specific packages in the environment. In such cases, I recommend using Google Colab (https://colab.research.google.com/). Colab typically downloads the latest versions, minimizing the occurrence of errors.

2. Please ensure that the format and content of the input file align with the specified requirements.

3. To pinpoint the exact step where the error occurs, I suggest running the code line by line and examining the output results.

I hope these suggestions prove helpful in resolving the issue you are facing.

**Comment by KaKa-sxyd** [comment]
Thank you for your timely reply, it is really my software package version problem

**Comment by hmgene** [comment]
my solution (please inform me if this is your intend):
```

def to_prob(df, groupby):
    sums = df.groupby(groupby).sum(min_count=1)
    sums = pd.merge(df, sums, how='left', on=groupby)
    #HMK
    if( groupby=="start" ):
       sums = sums.drop(columns=['start', 'end_x', 'end_y'])
    else:
       sums = sums.drop(columns=['start_x','start_y','end'])
    #sums = sums.drop(columns=['start', 'end'])

```
