### ISSUE TITLE
your readme is different from your  test result of the demo files

### ISSUE THREAD

**Issue by xiaobearxiaobear** [xryanglab/SCASL#4]
i have many question about your  readme: 
in your results: "normalized_matrix: The final AS probability matrix, the rows correspond to sites, while the columns represent cells." columns represent cells!columns represent cells!columns represent cells! but, i see the columns represent SRR* of each sample, so,How do you make a column represent  cells, and how do you generate the label file????????  I have serious doubts about your algorithm.......

**Comment by kokox10** [comment]
In the SRA database, each SRR* file corresponds to the sequencing information of individual cells in the context of single-cell sequencing data. Consequently, SRR* represents a distinct cell, with each column in the dataset denoting a specific cell, aligning precisely with the details outlined in our readme file. Following the execution of the SCASL program, the label file will be automatically generated within the user-defined directory (as specified by the parameter -label_file) you have designated. Please note that if you are utilizing bulk sequencing data, where each SRR* represents a sample, it is not feasible to obtain the matrix of a single cell. Such analysis falls outside the scope of our method's intended objective.

**Comment by xiaobearxiaobear** [comment]
Just now I was looking at the difference between smart-seq and 10x, and I will understand that each of your srr* is a cell, and all the resulting columns are srr*, which is also a cell. So I have a question: I saw that one of your articles also used 10x single cell sequencing, and I was wondering how you became according to barcode? And you also said at the end of the article that 10x single cells can be used, so the big question is how to extract the cell information from a sample bam file

**Comment by xiaobearxiaobear** [comment]
Just now I was looking at the difference between smart-seq and 10x, and I will understand that each of your srr* is a cell, and all the resulting columns are srr*, which is also a cell. So I have a question: I saw that one of your articles also used 10x single cell sequencing, and I was wondering how you became according to barcode? And you also said at the end of the article that 10x single cells can be used, so the big question is how to extract the cell information from a sample bam file
